from django.conf.urls import patterns, url
from views import (AreaCheckView,
                   AreaListAllCasesView,
                   AreaListView,
                   CatalogCheckView,
                   CatalogListAllCasesView,
                   CatalogListView,
                   )

urlpatterns = patterns('',
                       url(r'^$',
                           AreaListView.as_view(),
                           name="area_list"),
                       url(r'^(?P<area>\d+)$',
                           AreaCheckView.as_view(),
                           name="area_check"),
                       url(r'^all/(?P<area>\d+)$',
                           AreaListAllCasesView.as_view(),
                           name="area_list_all_cases"),
                       url(r'^catalog$',
                           CatalogListView.as_view(),
                           name="catalog_list"),
                       url(r'^catalog/error/(?P<catalog>\d+)$',
                           CatalogCheckView.as_view(),
                           name="catalog_check"),
                       url(r'^catalog/detail/(?P<catalog>\d+)$',
                           CatalogListAllCasesView.as_view(),
                           name="catalog_list_all_cases"),
                       )
